kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
  namespace: mongoshop-database
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  type: ClusterIP
  

